fix: Use deprecated object keys
viur-framework/vi-vue-utils pull request #11
Opened 2024-05-14 15:15 UTC by KadirBalku

needs further testing before Merge can be resolved

2024-05-14 16:45 UTC, sveneberth requested changes

2024-05-14 16:45 UTC, sveneberth commented on packages/viur-vue-utils/bones/edit/default/textBone.vue
> +      v-if="boneState.bonestructure['valid_html']"
If you use an old core this should still work IMO, so I would support both:
```suggestion
      v-if="boneState.bonestructure['valid_html'] ?? boneState.bonestructure['validHtml']"
```

2024-06-07 17:40 UTC, sveneberth commented
Hello @KadirBalku @akelch , can we fix this soon? Currently I don't have a wysiwyg editor in my project :( ...

2024-06-07 17:53 UTC, KadirBalku commented
> Hello @KadirBalku @akelch , can we fix this soon? Currently I don't have a wysiwyg editor in my project :( ...

does this change need to aplied to the viur admin ?

2024-06-07 18:51 UTC, sveneberth commented
> > Hello @KadirBalku @akelch , can we fix this soon? Currently I don't have a wysiwyg editor in my project :( ...
> 
> has this change to be aplied to the viur admin ?

yes

2024-06-18 12:23 UTC, merged